# Generated by Django 3.0.3 on 2020-02-21 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1000, null=True)),
                ('rank', models.IntegerField(choices=[(5, 5), (10, 10), (15, 15), (20, 20)], default=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizTaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_answer', models.CharField(default='first answer', max_length=1000, null=True)),
                ('second_answer', models.CharField(default='second answer', max_length=1000, null=True)),
                ('third_answer', models.CharField(default='third_answer', max_length=1000, null=True)),
                ('fourth_answer', models.CharField(default='fourth answer', max_length=1000, null=True)),
                ('correct_answer', models.CharField(default=None, max_length=1000, null=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='QA.MultipleChoiceQuestion')),
            ],
        ),
    ]
